# Site settings
title: Pierre Le Merre
email: pierrepierrepierre.lemerre@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Pierre Le Merre
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.pierrelemerre.com/" # the base hostname & protocol for your site
twitter_username: Pierre_Le_Merre
github_username:  PierreLeMerre

source:      .
destination: ./_site
plugins_dir: ./_plugins

# Build settings
markdown: kramdown
